# This workflow will prepare every thing required to proceed with a PR
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on:
  push:
    branches:
      - develop-luca

jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # TAG
  release-tag:
    env:
      ENTANDO_OPT_USE_PPL_TAG: ${{ secrets.ENTANDO_OPT_USE_PPL_TAG }}
      PPL_CONTEXT: ${{ toJson(github) }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      REPO_FOLDER: "repo_folder"
      ENTANDO_OPT_LOG_LEVEL: DEBUG
    runs-on: ubuntu-latest
    steps:
      - name: "CONFIGURE ENTANDO-PIPELINES"
        run: |
          source <(curl -qsL "https://raw.githubusercontent.com/entando/entando-pipelines/engine-exp/macro/install.sh")
      - name: "Checkout"
        run: |
          ~/ppl-run checkout-branch "CHECKOUT FOR RELEASE TAG" base "$REPO_FOLDER" "${{ secrets.ENTANDO_BOT_TOKEN }}"
      - name: "Tag version"
        run: |
          ~/ppl-run start-release "TAG GENERATION" new-version "$REPO_FOLDER"
