# Tag Release workflow:
# - build
# - tests
# - owasp checks
# - sonacloud checks

name: After Merge

on:
  push:
    branches:
      - develop-luca

jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # TAG
  add-release-tag:
    env:
      PPL_CONTEXT: ${{ toJson(github) }}
      ENTANDO_OPT_USE_PPL_TAG: ${{ secrets.ENTANDO_OPT_USE_PPL_TAG }}
      ENTANDO_OPT_REPO_BOM_URL: ${{ secrets.ENTANDO_OPT_REPO_BOM_URL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      REPO_FOLDER: "local-checkout"
    runs-on: ubuntu-latest
    steps:
      - name: "ADD RELEASE TAG"
        run: |
          source <(curl -qsL "https://raw.githubusercontent.com/entando/entando-pipelines/${ENTANDO_OPT_USE_PPL_TAG}/macro/install.sh")
          ~/ppl-run \
            pr-status-report \
            .. checkout-branch base \
              --id "CHECKOUT-BASE" \
              --lcd "$REPO_FOLDER" \
              --toekn "${{ secrets.ENTANDO_BOT_TOKEN }}" \
            .. release prepare-tag-release \
              --id "TAG-RELEASE" \
              --lcd "$REPO_FOLDER"

