# Tag Release workflow:
# - build
# - tests
# - owasp checks
# - sonacloud checks

name: After Merge

on:
  push:
    branches:
      - develop-luca

jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # TAG
  add-release-tag:
    env:
      PPL_CONTEXT: ${{ toJson(github) }}
      ENTANDO_OPT_USE_PPL_TAG: ${{ secrets.ENTANDO_OPT_USE_PPL_TAG }}
      ENTANDO_OPT_REPO_BOM_URL: ${{ secrets.ENTANDO_OPT_REPO_BOM_URL }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      REPO_FOLDER: "local-checkout"
      ENTANDO_OPT_LOG_LEVEL: TRACE
    runs-on: ubuntu-latest
    steps:
      - name: "ADD RELEASE TAG"
        run: |
          bash <(curl -qsL "https://raw.githubusercontent.com/entando/entando-pipelines/${ENTANDO_OPT_USE_PPL_TAG}/macro/install.sh")
          cat ~/.entando/ppl/entando-pipelines/macro/github/checkout-branch.sh
          cd ~/.entando/ppl/entando-pipelines
          git branch
          git fetch --all
          git fetch --tags
          echo "$BRANCH" | sed -E 's/(.)/\1_/g'
          BRANCH="${ENTANDO_OPT_USE_PPL_TAG:-master}"
          git checkout -B "$BRANCH" "$BRANCH"
          echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

          ~/ppl-run pr-status-report \
          --AND checkout-branch base \
                --id "CHECKOUT-BASE" \
                --lcd "$REPO_FOLDER" \
                --token "${{ secrets.ENTANDO_BOT_TOKEN }}" \
          --AND release prepare-tag-release \
                --id "TAG-RELEASE" \
                --lcd "$REPO_FOLDER"
