# Tag Release workflow:
# - build
# - tests
# - owasp checks
# - sonacloud checks

name: tag-release

on:
  push:
    branches:
      - develop

jobs:
  finalize:
    env:
      ENTANDO_OPT_USE_PPL_TAG: ${{ secrets.ENTANDO_OPT_USE_PPL_TAG }}
      ENTANDO_OPT_LOG_LEVEL: TRACE
      PPL_CONTEXT: ${{ toJson(github) }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
      REPO_FOLDER: "repo_folder"
    runs-on: ubuntu-latest
      - name: "TAG-RELEASE WORKFLOW START"
        run: |
          source <(curl -qsL "https://raw.githubusercontent.com/entando/entando-pipelines/${ENTANDO_OPT_USE_PPL_TAG}/macro/install.sh")
          ~/ppl-run \
            pr-status-report --AND \
            checkout-pr-branch "$REPO_FOLDER" --AND \
            start-release "TAG-RELEASE" tag-release "$REPO_FOLDER" \
          ;
      - name: "Checkout"
        run: |
